all: DesSolution.java DesImageSolution.java DigitalSignatureSolution.java
	javac DesSolution.java DesImageSolution.java DigitalSignatureSolution.java
	java DesSolution
	java DesImageSolution
	java DigitalSignatureSolution

part1: DesSolution.class
	java DesSolution

part2: DesImageSolution.class
	java DesImageSolution

part3: DigitalSignatureSolution.class
	java DigitalSignatureSolution

clean:
	rm -f DesSolution.class
	rm -f DesImageSolution.class
	rm -f DigitalSignatureSolution.class