#!/bin/sh

echo "------------------------------"
echo "Attempting to ping www.csail.mit.edu..."
echo "------------------------------"
echo "Pinging www.csail.mit.edu with 10 packets, 56 bytes each, with an interval of 5 seconds between each packet sent..."
ping www.csail.mit.edu -c 10 -s 56 -i 5 | grep -e "ping statistics" -e "packet loss" -e "rtt min/avg/max/mdev"
echo "                              "
echo "Pinging www.csail.mit.edu with 10 packets, 512 bytes each, with an interval of 5 seconds between each packet sent..."
ping www.csail.mit.edu -c 10 -s 512 -i 5 | grep -e "ping statistics" -e "packet loss" -e "rtt min/avg/max/mdev"
echo "                              "
echo "Pinging www.csail.mit.edu with 10 packets, 1024 bytes each, with an interval of 5 seconds between each packet sent..."
ping www.csail.mit.edu -c 10 -s 1024 -i 5 | grep -e "ping statistics" -e "packet loss" -e "rtt min/avg/max/mdev"
echo "                              "

echo "------------------------------"
echo "Attempting to ping www.berkeley.edu..."
echo "------------------------------"
echo "Pinging www.berkeley.edu with 10 packets, 56 bytes each, with an interval of 5 seconds between each packet sent..."
ping www.berkeley.edu -c 10 -s 56 -i 5 | grep -e "ping statistics" -e "packet loss" -e "rtt min/avg/max/mdev"
echo "                              "
echo "Pinging www.berkeley.edu with 10 packets, 512 bytes each, with an interval of 5 seconds between each packet sent..."
ping www.berkeley.edu -c 10 -s 512 -i 5 | grep -e "ping statistics" -e "packet loss" -e "rtt min/avg/max/mdev"
echo "                              "
echo "Pinging www.berkeley.edu with 10 packets, 1024 bytes each, with an interval of 5 seconds between each packet sent..."
ping www.berkeley.edu -c 10 -s 1024 -i 5 | grep -e "ping statistics" -e "packet loss" -e "rtt min/avg/max/mdev"
echo "                              "

echo "------------------------------"
echo "Attempting to ping www.usyd.edu.au..."
echo "------------------------------"
echo "Pinging www.usyd.edu.au with 10 packets, 56 bytes each, with an interval of 5 seconds between each packet sent..."
ping www.usyd.edu.au -c 10 -s 56 -i 5 | grep -e "ping statistics" -e "packet loss" -e "rtt min/avg/max/mdev"
echo "                              "
echo "Pinging www.usyd.edu.au with 10 packets, 512 bytes each, with an interval of 5 seconds between each packet sent..."
ping www.usyd.edu.au -c 10 -s 512 -i 5 | grep -e "ping statistics" -e "packet loss" -e "rtt min/avg/max/mdev"
echo "                              "
echo "Pinging www.usyd.edu.au with 10 packets, 1024 bytes each, with an interval of 5 seconds between each packet sent..."
ping www.usyd.edu.au -c 10 -s 1024 -i 5 | grep -e "ping statistics" -e "packet loss" -e "rtt min/avg/max/mdev"
echo "                              "

echo "------------------------------"
echo "Attempting to ping www.kyoto-u.ac.jp..."
echo "------------------------------"
echo "Pinging www.kyoto-u.ac.jp with 10 packets, 56 bytes each, with an interval of 5 seconds between each packet sent..."
ping www.kyoto-u.ac.jp -c 10 -s 56 -i 5 | grep -e "ping statistics" -e "packet loss" -e "rtt min/avg/max/mdev"
echo "                              "
echo "Pinging www.kyoto-u.ac.jp with 10 packets, 512 bytes each, with an interval of 5 seconds between each packet sent..."
ping www.kyoto-u.ac.jp -c 10 -s 512 -i 5 | grep -e "ping statistics" -e "packet loss" -e "rtt min/avg/max/mdev"
echo "                              "
echo "Pinging www.kyoto-u.ac.jp with 10 packets, 1024 bytes each, with an interval of 5 seconds between each packet sent..."
ping www.kyoto-u.ac.jp -c 10 -s 1024 -i 5 | grep -e "ping statistics" -e "packet loss" -e "rtt min/avg/max/mdev"
